//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faidv2.FaidView.M1 {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class M1Ressourcen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal M1Ressourcen() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Faidv2.FaidView.M1.M1Ressourcen", typeof(M1Ressourcen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kontoname: ähnelt.
        /// </summary>
        public static string InputKontoName {
            get {
                return ResourceManager.GetString("InputKontoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler bei der Konvertierung ähnelt.
        /// </summary>
        public static string MsgBoxKonvertierungFehlerUeberschrift {
            get {
                return ResourceManager.GetString("MsgBoxKonvertierungFehlerUeberschrift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Laden ähnelt.
        /// </summary>
        public static string MsgBoxLadeFehlerUeberschrift {
            get {
                return ResourceManager.GetString("MsgBoxLadeFehlerUeberschrift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Speichern ähnelt.
        /// </summary>
        public static string MsgBoxSpeichernFehlerUeberschrift {
            get {
                return ResourceManager.GetString("MsgBoxSpeichernFehlerUeberschrift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Konto geladen ähnelt.
        /// </summary>
        public static string StatusKeinKonto {
            get {
                return ResourceManager.GetString("StatusKeinKonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei &quot;{0}&quot; konnte nicht geladen werden! ähnelt.
        /// </summary>
        public static string StatusLadefehler {
            get {
                return ResourceManager.GetString("StatusLadefehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei &quot;{0}&quot; konnte nicht gespeichert werden! ähnelt.
        /// </summary>
        public static string StatusSpeichernFehler {
            get {
                return ResourceManager.GetString("StatusSpeichernFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Konto ähnelt.
        /// </summary>
        public static string StdKontoName {
            get {
                return ResourceManager.GetString("StdKontoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Storniere {0}... ähnelt.
        /// </summary>
        public static string StorniereBuchung {
            get {
                return ResourceManager.GetString("StorniereBuchung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Faid v2 ähnelt.
        /// </summary>
        public static string TitelAllgemein {
            get {
                return ResourceManager.GetString("TitelAllgemein", resourceCulture);
            }
        }
    }
}
