//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faidv2.FaidView.M2 {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class M2Ressourcen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal M2Ressourcen() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Faidv2.FaidView.M2.M2Ressourcen", typeof(M2Ressourcen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Additiv ähnelt.
        /// </summary>
        public static string BewegungAdd {
            get {
                return ResourceManager.GetString("BewegungAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gleichsetzend ähnelt.
        /// </summary>
        public static string BewegungGleich {
            get {
                return ResourceManager.GetString("BewegungGleich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subtraktiv ähnelt.
        /// </summary>
        public static string BewegungSub {
            get {
                return ResourceManager.GetString("BewegungSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgaben ähnelt.
        /// </summary>
        public static string ModusAusgaben {
            get {
                return ResourceManager.GetString("ModusAusgaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transaktion ähnelt.
        /// </summary>
        public static string ModusBewegung {
            get {
                return ResourceManager.GetString("ModusBewegung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einkommen ähnelt.
        /// </summary>
        public static string ModusEinkommen {
            get {
                return ResourceManager.GetString("ModusEinkommen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zinsen ähnelt.
        /// </summary>
        public static string ModusZinsen {
            get {
                return ResourceManager.GetString("ModusZinsen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde kein zu verbuchender Betrag angegeben. ähnelt.
        /// </summary>
        public static string MsgBoxKeinWert {
            get {
                return ResourceManager.GetString("MsgBoxKeinWert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        public static string MsgBoxKeinWertUeberschrift {
            get {
                return ResourceManager.GetString("MsgBoxKeinWertUeberschrift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzerdefiniert ähnelt.
        /// </summary>
        public static string PeriodeBenutzerdefiniert {
            get {
                return ResourceManager.GetString("PeriodeBenutzerdefiniert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dienstag ähnelt.
        /// </summary>
        public static string PeriodeDienstag {
            get {
                return ResourceManager.GetString("PeriodeDienstag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Donnerstag ähnelt.
        /// </summary>
        public static string PeriodeDonnerstag {
            get {
                return ResourceManager.GetString("PeriodeDonnerstag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Freitag ähnelt.
        /// </summary>
        public static string PeriodeFreitag {
            get {
                return ResourceManager.GetString("PeriodeFreitag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jährlich ähnelt.
        /// </summary>
        public static string PeriodeJaehrlich {
            get {
                return ResourceManager.GetString("PeriodeJaehrlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mittwoch ähnelt.
        /// </summary>
        public static string PeriodeMittwoch {
            get {
                return ResourceManager.GetString("PeriodeMittwoch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monatlich ähnelt.
        /// </summary>
        public static string PeriodeMonatlich {
            get {
                return ResourceManager.GetString("PeriodeMonatlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Montag ähnelt.
        /// </summary>
        public static string PeriodeMontag {
            get {
                return ResourceManager.GetString("PeriodeMontag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Samstag ähnelt.
        /// </summary>
        public static string PeriodeSamstag {
            get {
                return ResourceManager.GetString("PeriodeSamstag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sonntag ähnelt.
        /// </summary>
        public static string PeriodeSonntag {
            get {
                return ResourceManager.GetString("PeriodeSonntag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wöchentlich ähnelt.
        /// </summary>
        public static string PeriodeWoechentlich {
            get {
                return ResourceManager.GetString("PeriodeWoechentlich", resourceCulture);
            }
        }
    }
}
